# Frequency limits, NESO (2026, ECC.A.3)
# raw constants, units are in the names
from __future__ import annotations
from enum import Enum

GRID_CODE_NOMINAL_FREQUENCY_HZ = 50.0; GRID_CODE_FSM_DROOP_MINIMUM = 0.03
GRID_CODE_FSM_DROOP_MAXIMUM = 0.05; GRID_CODE_FSM_DEADBAND_HZ = 0.0; GRID_CODE_FSM_INSENSITIVITY_HZ = 0.015
GRID_CODE_FSM_COMBINED_BAND_WIDTH_HZ = 0.03
GRID_CODE_FSM_RESPONSE_RANGE_FRACTION = 0.1
GRID_CODE_FSM_INITIAL_DELAY_WITH_INERTIA_SECONDS = 2.0
GRID_CODE_FSM_INITIAL_DELAY_WITHOUT_INERTIA_SECONDS = 1.0
GRID_CODE_FSM_ACTIVATION_SECONDS = 10.0
GRID_CODE_TARGET_FREQUENCY_MINIMUM_HZ = 49.9
GRID_CODE_TARGET_FREQUENCY_MAXIMUM_HZ = 50.1
GRID_CODE_TARGET_FREQUENCY_MAXIMUM_STEP_HZ = 0.05
GRID_CODE_REFERENCE_FREQUENCY_DEVIATION_HZ = 0.5
GRID_CODE_MAXIMUM_MRL_FRACTION = 0.55
GRID_CODE_MAXIMUM_MSOL_FRACTION = 0.65
GRID_CODE_PRIMARY_START_SECONDS = 10.0
GRID_CODE_PRIMARY_END_SECONDS = 30.0
GRID_CODE_SECONDARY_START_SECONDS = 30.0
GRID_CODE_SECONDARY_END_SECONDS = 30.0 * 60.0
GRID_CODE_HIGH_START_SECONDS = 10.0
GRID_CODE_RESPONSE_RESTORATION_MINUTES = 20.0
GRID_CODE_FREQUENCY_RECORDING_MINIMUM_HZ = 1.0
NESO_GUIDANCE_FREQUENCY_SUBMISSION_HZ = 10.0


class FrequencyResponseService(Enum):
    PRIMARY = 'primary'
    SECONDARY = "secondary"
    HIGH = 'high'
